<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
            "http://www.w3.org/TR/html4/loose.dtd">
<HTML>

<HEAD>
<TITLE>FLORA Community WEB- Demo of Templates (PHP3)</TITLE>
<META name="description" content="How to use Templates when
authoring FLORA.ORG documents">
<META name="keywords" content="PHP, SSI, Templates">
</HEAD>

<SCRIPT LANGUAGE="php">include("template-top.php3");</SCRIPT>

<P>This is the text that would be put at the top of the page.  This text
appears beside the buttons and are put into a column.  Remember, only
use the PHP version of this file if it is included as part of some
software. Remember also that the include() directive takes a pathname and
you need to make it relative to where you are including it (Or use a full
pathname).


<SCRIPT
LANGUAGE="php">include("template-bottom.php3");</SCRIPT>
</HTML>
