# Site settings
title: Getting Open Source Logic INto Governments (GOSLING) Community
email: ""
description: > # this means to ignore newlines until "baseurl:"
  GOSLING (Getting Open Source Logic INto Governments) is a voluntary,
  informal learning and knowledge-sharing community of practice, involving
  civil servants and other citizens who actively assist the engagement of
  free/libre open source methods and software solutions in government
  operations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.goslingcommunity.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
  - README.md
  - CNAME
  - script
  - vendor
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-redirect-from
